package com.kmilo2506.annotationssample.fragments;

import android.content.Intent;
import android.support.v4.app.Fragment;
import android.widget.Button;
import android.widget.EditText;

import com.kmilo2506.annotationssample.R;
import com.kmilo2506.annotationssample.activities.ResultActivity_;

import org.androidannotations.annotations.Click;
import org.androidannotations.annotations.EFragment;
import org.androidannotations.annotations.ViewById;

/**
 * Created by Camilo Sepulveda on 1/27/16.
 */

/**
 * The @EFragment annotation works similar to @EActivity.
 * In this case we pass the fragment's layout as an annotation's
 * parameter. The annotation will take care of inflating that layout.
 */
@EFragment(R.layout.form_layout)
public class FormFragment extends Fragment {

    /**
     * The @ViewById annotation takes care of searching and parsing
     * the views using the view's id passed as a parameter.
     * For this to work the View objects MUST NOT be private.
     */
    @ViewById(R.id.edit_weight)
    EditText mWeight;

    @ViewById(R.id.edit_height)
    EditText mHeight;

    @ViewById(R.id.button_calc_bmi)
    Button mCalcBmi;

    /**
     * The @Click annotations works similar to the @ViewById annotation.
     * Pass the id of the view as a parameter and the annotation will
     * set a clickListener for that view that will trigger the method
     * you define next to the annotation. This method MUST BE void and
     * receive no parameters (As of the AndroidAnnotations version used
     * in this project).
     */
    @Click(R.id.button_calc_bmi)
    void calcBmi(){
        double bmi = Integer.valueOf(mWeight.getText().toString()) /
                (Float.valueOf(mHeight.getText().toString()) * Float.valueOf(mHeight.getText().toString()));

        // Remember: Reference the underscored activities generated by the framework
        Intent intent = ResultActivity_.newIntent(getActivity(), bmi);
        // DON'T DO: Intent intent = ResultActivity.newIntent(getActivity(), bmi);
        startActivity(intent);
    }

}
